/**
 * Compiles the exercise markdown corpus into JSON for the site.
 *
 * Usage: npm run build:content
 * Reads:  ../ToBI-approach/*.md, ../IPA-Approach/*.md
 * Writes: public/content/collections.json         (index of collections)
 *         public/content/<approach>/<slug>.json   (exercises per collection)
 *         content-validation-report.md            (parse issues, not committed)
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';
import { parseTobiMarkdown } from '../src/content/parseTobi';
import { parseIpaMarkdown } from '../src/content/parseIpa';
import type { Approach, CollectionMeta, ParseIssue, ParseResult } from '../src/content/types';

const REPO_ROOT = resolve(import.meta.dirname, '..', '..');
const OUT_DIR = resolve(import.meta.dirname, '..', 'public', 'content');
const REPORT_PATH = resolve(import.meta.dirname, '..', 'content-validation-report.md');

const SOURCES: { approach: Approach; dir: string; parse: typeof parseTobiMarkdown }[] = [
  { approach: 'tobi', dir: join(REPO_ROOT, 'ToBI-approach'), parse: parseTobiMarkdown },
  { approach: 'ipa', dir: join(REPO_ROOT, 'IPA-Approach'), parse: parseIpaMarkdown },
];

const SKIP_FILES = new Set(['INSTRUCTIONS.md']);

function titleFromMarkdown(md: string, fallback: string): string {
  const m = md.match(/^#\s+(.+)$/m);
  return m ? m[1].trim() : fallback;
}

const collections: CollectionMeta[] = [];
const allIssues: ParseIssue[] = [];
let totalExercises = 0;

rmSync(OUT_DIR, { recursive: true, force: true });

for (const source of SOURCES) {
  const files = readdirSync(source.dir).filter(
    (f) => f.endsWith('.md') && !SKIP_FILES.has(f),
  );
  mkdirSync(join(OUT_DIR, source.approach), { recursive: true });

  for (const file of files.sort()) {
    const md = readFileSync(join(source.dir, file), 'utf8');
    const slug = basename(file, '.md');
    const result: ParseResult = source.parse(md, { file: `${source.approach}/${file}`, collection: slug });

    collections.push({
      slug,
      approach: source.approach,
      title: titleFromMarkdown(md, slug),
      exerciseCount: result.exercises.length,
      file: `${source.approach}/${file}`,
    });
    allIssues.push(...result.issues);
    totalExercises += result.exercises.length;

    writeFileSync(
      join(OUT_DIR, source.approach, `${slug}.json`),
      JSON.stringify(result.exercises),
    );
  }
}

writeFileSync(join(OUT_DIR, 'collections.json'), JSON.stringify(collections, null, 2));

const lines: string[] = [
  '# Content validation report',
  '',
  `Generated by scripts/build-content.ts`,
  '',
  `- Collections: ${collections.length}`,
  `- Exercises parsed: ${totalExercises}`,
  `- Issues: ${allIssues.length}`,
  '',
  '## Exercises per collection',
  '',
  ...collections.map((c) => `- ${c.file}: ${c.exerciseCount}`),
  '',
  '## Issues',
  '',
];
if (allIssues.length === 0) {
  lines.push('None.');
} else {
  const byFile = new Map<string, ParseIssue[]>();
  for (const issue of allIssues) {
    const list = byFile.get(issue.file) ?? [];
    list.push(issue);
    byFile.set(issue.file, list);
  }
  for (const [file, issues] of byFile) {
    lines.push(`### ${file} (${issues.length})`, '');
    for (const i of issues.slice(0, 50)) {
      lines.push(`- L${i.line}: ${i.message} — \`${i.excerpt}\``);
    }
    if (issues.length > 50) lines.push(`- …and ${issues.length - 50} more`);
    lines.push('');
  }
}
writeFileSync(REPORT_PATH, lines.join('\n'));

console.log(`Parsed ${totalExercises} exercises from ${collections.length} collections.`);
console.log(`${allIssues.length} issues — see ${REPORT_PATH}`);
